version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: terencegaffudsu/simple-crm
          tag: 1.0.1
      - docker/push:
          image: terencegaffudsu/simple-crm
          tag: 1.0.1
  deploy:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - setup_remote_docker      
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: | 
              heroku container:login
              heroku container:push web -a simple_crm
              heroku container:release web -a simple_crm


workflows:
  simple_workflow:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
      - deploy:
          requires:
            - publish